image: Visual Studio 2016

clone_folder: c:\projects\odin
environment:
  global:
    STACK_ROOT: c:\\projects\odin\sr

install:
# http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
- curl -sS -ostack.zip -L https://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe
- stack setup > nul
- stack exec -- pacman -Syu --noconfirm
- stack exec -- pacman -S --noconfirm mingw-w64-x86_64-pkg-config mingw-w64-x86_64-SDL2 mingw-w64-x86_64-freetype

build_script:
- stack --no-terminal --no-haddock build
