resolver: nightly-2017-11-02

packages:
- odin-engine

- location:
    git: https://github.com/ublubu/shapes.git
    commit: ddee4ccce4ac4d1f6d526477b66451aa578b0e0f
  subdirs:
  - shapes
  - shapes-math
  extra-dep: true

- location:
    git: https://github.com/schell/reflex
    commit: fc69b9793218578e76e6eb79991ccdf665c88636
  extra-dep: true

- location:
    git: https://github.com/schell/reflex-sdl2
    commit: b2089accef02ee218a8ec7d909471b34f824f09e
  extra-dep: true

extra-deps:
- aeson-tiled-0.0.0.1
- freetype2-0.1.1
- gelatin-0.1.0.0
- gelatin-shaders-0.1.0.0
- gelatin-gl-0.1.0.0
- gelatin-sdl2-0.1.1.0
- gelatin-freetype2-0.1.0.0
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- sdl2-2.3.0
flags: {}
extra-package-dbs: []
