flags: {}
packages:
- '.'
- '../gelatin/gelatin-core'
- '../gelatin/gelatin-picture'
- '../gelatin/gelatin-gl'
- '../gelatin/gelatin-sdl2'
- '../renderable'
- '../htiled'
- '../varying'
- '../sdl2'

- location: '../shapes'
  subdirs:
  - shapes
  - shapes-math

extra-deps:
- FontyFruity-0.5.3.2
- freer-0.2.3.0

resolver: lts-6.7
#resolver: nightly-2016-07-14
