flags: {}
packages:

- location:
    git: https://github.com/schell/gelatin.git
    commit: 51b30f20c545e77aa13c0450cdccb668f55dc902
  subdirs:
  - gelatin
  - gelatin-gl
  - gelatin-sdl2
  - gelatin-freetype2
- location:
    git: https://github.com/schell/renderable.git
    commit: fda35ce6d0f02f3e29bf8168305f8ac5421f40fd
- location:
    git: https://github.com/schell/htiled.git
    commit: b008faec3971d7088e4570abc42f94b0b510dde3
- location:
    git: https://github.com/schell/varying.git
    commit: aca7eeb11869af9345fb5fc3233508a1c29e7783
- location:
    git: https://github.com/schell/sdl2.git
    commit: aff05d74b6a11969c880ab410193ff44ec0905ee

- location:
    git: https://github.com/schell/shapes.git
    commit: 0f8a187695e9cd1228e79bb8a51f5a6a6de3469e
  subdirs:
  - shapes
  - shapes-math

- location:
    git: https://github.com/lukexi/halive.git
    commit: c1ded911d7cd37df4192aaa4f05c05f53b796bb3

extra-deps:
- FontyFruity-0.5.3.2
- freetype2-0.1.1

resolver: lts-7.1
#resolver: nightly-2016-07-14
#resolver: nightly-2016-08-17
