flags: {}
packages:
- .

- ./odin-engine

- location:
    git: https://github.com/schell/gelatin
    commit: 71cdb01965cd752f34209f6c462e4a679b53324e
  subdirs:
  - gelatin
  - gelatin-shaders
  - gelatin-gl
  - gelatin-sdl2
  - gelatin-freetype2
  extra-dep: true

- location:
    git: https://github.com/schell/htiled.git
    commit: b008faec3971d7088e4570abc42f94b0b510dde3
  extra-dep: true

- location:
    git: https://github.com/schell/varying.git
    commit: 15c44f7ab5cb459ad053b58b3776d226d56b0dc7
  extra-dep: true

- location:
    git: https://github.com/schell/shapes.git
    commit: 0f8a187695e9cd1228e79bb8a51f5a6a6de3469e
  subdirs:
  - shapes
  - shapes-math
  extra-dep: true

- location:
    git: https://github.com/phadej/gl.git
    commit: e7fd09f260ea5986bbd0addb9e41384ca79c004e
  extra-dep: true

- location:
    git: https://github.com/schell/halive.git
    commit: 48ba4f22649bb9372fc3fbc6e94f25df20dbae2c
  extra-dep: true

- location:
    git: https://github.com/IxpertaSolutions/freer-effects.git
    commit: da3b972379102c6cbde36879ff8f0f8c99bd4c81
  extra-dep: true

extra-deps:
- freetype2-0.1.1

resolver: lts-8.0
