resolver: lts-9.11

packages:
- odin-engine

- location:
    git: https://github.com/ublubu/shapes.git
    commit: ddee4ccce4ac4d1f6d526477b66451aa578b0e0f
  subdirs:
  - shapes
  - shapes-math
  extra-dep: true

- location:
    git: https://github.com/schell/halive.git
    commit: 48ba4f22649bb9372fc3fbc6e94f25df20dbae2c
  extra-dep: true

- location:
    git: https://github.com/reflex-frp/reflex
    commit: a6ee264850cf80c55e8fed99575107a44af57081
  extra-dep: true

- location:
    git: https://github.com/schell/QuadTree
    commit: bd11166e50e5f2f4ade87613520aaf82e23cc9eb
  extra-dep: true

extra-deps:
- aeson-tiled-0.0.0.1
- freetype2-0.1.1
- gelatin-0.1.0.0
- gelatin-shaders-0.1.0.0
- gelatin-gl-0.1.0.0
- gelatin-sdl2-0.1.1.0
- gelatin-freetype2-0.1.0.0
- prim-uniq-0.1.0.1
- QuadTree-0.11.0
- ref-tf-0.4.0.1
- reflex-sdl2-0.2.0.0
- sdl2-2.3.0
flags: {}
extra-package-dbs: []
